### ISSUE TITLE
E: Packages were downgraded and -y was used without --allow-downgrades. [bug]

### ISSUE THREAD

**Issue by gallowaystorm** [BobAnkh/auto-generate-changelog#103]
## Describe the bug
When running the action, the docker build for BobAnkh/auto-generate-changelog@v1.2.3 & BobAnkh/auto-generate-changelog@v1.2.2 are failing with the following error:

E: Packages were downgraded and -y was used without --allow-downgrades.

## To Reproduce

Run the action from github actions.  The docker build for the action will fail.

> **NOTE**:Self-contained, minimal reproducing samples are extremely helpful and will expedite addressing your issue

## Expected behavior

No failure

## Screenshots

![error](https://user-images.githubusercontent.com/49792674/216084436-bc4822da-7b16-4520-8b67-677020fb2bf0.PNG)

## Environment

- Device: \[e.g. iPhone6]
- OS: \[e.g. Ubuntu 18.04LTS]
- Browser \[e.g. chrome, safari]
- Version \[e.g. 22]

**Comment by BobAnkh** [comment]
Thank you for reporting this bug and I can reproduce it. I will fix it as soon as possible.

**Comment by BobAnkh** [comment]
This should be fixed in v1.2.4(the latest version), can you please try it to see if the bug is gone?

**Comment by gallowaystorm** [comment]
It looks like it did work.  Thanks!
