### ISSUE TITLE
[enhancement] add an option to choose whether to use `<scope>`

### ISSUE THREAD

**Issue by BobAnkh** [BobAnkh/auto-generate-changelog#11]
## Is your feature request related to a problem? Please describe

The changelog generater is designed for commits that follows angularjs's convention. The `<header>` should be like this: `<type>(<scope>): <subject>`. However, `<scope>` is optional in many projects, so I think it is better for users to choose if generater detects `<scope>`

## Description of the new feature/enhancement

An new option to choose if detect `<scope>` in commit message `<header>`. It is set to `true` be default, which means to detect it. 

## Proposed technical implementation details (optional)

If this new option is set to `false`, then the program will match `<type>:` or `<type>(<scope>):` but ignore `<scoope>`.

**Comment by BobAnkh** [comment]
I think we should list commits without `<scope>` in a part called `others` when this new option is set to true, as `<scope>` is often an optional part to developers.

**Comment by sruehl** [comment]
this one defines it as optional https://www.conventionalcommits.org/en/v1.0.0/

**Comment by sruehl** [comment]
related bug https://github.com/BobAnkh/auto-generate-changelog/issues/73

**Comment by sruehl** [comment]
so reading through https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines it is [stated](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#commit-message-format) that `The header is mandatory and the scope of the header is optional`. So even in the original angular spec it's defined as optional. So I would suggest closing [this](https://github.com/BobAnkh/auto-generate-changelog/issues/11) issue in favor of https://github.com/BobAnkh/auto-generate-changelog/issues/73 which fixes this "bug" with https://github.com/BobAnkh/auto-generate-changelog/pull/74

**Comment by BobAnkh** [comment]
@sruehl 

When I first created this repo, I suppose myself to commit all with a scope. But I think it is also very important to pick up commits without scope, so I open this issue.

You propose a good suggestion. I will take into account of this when I am free this week. Thank you very much!
