### ISSUE TITLE
[bug] using the pull request config removes every other changelog entry

### ISSUE THREAD

**Issue by mmattbtw** [BobAnkh/auto-generate-changelog#82]
## Describe the bug
When pushing a new update, the workflow updates the the current update, but then removes the other entries.

## To Reproduce

> **NOTE**:Self-contained, minimal reproducing samples are extremely helpful and will expedite addressing your issue

1. Make an update
2. Wait for workflow to update changelog
3. Observe

## Expected behavior

It shouldn't delete the other entries, and should only update that current update

## Screenshots
https://github.com/mmattDonk/AI-TTS-Donations/pull/155/files

(backup screenshots just in case that pr changes)
![image](https://user-images.githubusercontent.com/30363562/158010275-b11c47b9-496f-4c93-93e8-7c74b7221fb0.png)
![image](https://user-images.githubusercontent.com/30363562/158010279-1e2b65e3-e200-4b4a-95f4-1a73d3a0d96f.png)
![image](https://user-images.githubusercontent.com/30363562/158010280-7609cdda-a72c-4735-a3c0-f0d36c7d5ec2.png)

## Environment

https://github.com/mmattDonk/AI-TTS-Donations/blob/main/.github/workflows/changelog.yml

**Comment by BobAnkh** [comment]
Hello, I don't understand what do you mean by `should only update the current update`?

Could you please give a simple example of what do you expect and what this workflow gives? Or what shouldb't be done within the workflow?

**Comment by mmattbtw** [comment]
@BobAnkh By "current update" I mean the commit/pull request/tag that isn't already on the Changelog, that is being updated by the workflow. So when I commit "feat(core): added feature", the change log updated with that commit, that would be the "current update". 

What the workflow shouldn't do (what it's doing in my case) is delete every other update information.

**Comment by BobAnkh** [comment]
@mmattbtw Hi, do you mean an incremental changelog? For example, when you push a new commit, then only add this commit into your current changelog, not affecting the remaining content? If this is what you are talking about, then I'm afraid it is not supported yet and this should not be concerned as a bug. 

I'm generate the changelog release/tag by release/tag, and I'm planning to support the feature that only re-generate the last several releases though, for performance purpose. However, this feature may not come soon.

**Comment by BobAnkh** [comment]
@mmattbtw 

The problem should be partially alleviated in the new release v1.2.1 with incremental changelog generation implemented.
