### ISSUE TITLE
Unrelease part should be removed

### ISSUE THREAD

**Issue by kambpr01** [BobAnkh/auto-generate-changelog#87]
change log is created but that Unrelease needs to be removed

**Comment by BobAnkh** [comment]
If I add a parameter option to close this feature, that is to say, will not include these unreleased commits, will it be nice for you to work? It will be served as the default to remove unreleased commits.

**Comment by BobAnkh** [comment]
@kambpr01 

The problem should be solved in the new release v1.2.1.
